package org.terraform.tree;

public class FractalCoralBuilder {
//    case BROWN_MUSHROOM_BASE:
//        this.setBaseHeight(3)
//                .setBaseThickness(3)
//                .setThicknessDecrement(0)
//                .setMaxDepth(2)
//                .setFractalThreshold(4)
//                .setLeafRadius(0)
//                .setLogType(Material.MUSHROOM_STEM)
//                .setLengthDecrement(0)
//                .setMinBend(0.2 * Math.PI / 6)
//                .setMaxBend(0.4 * Math.PI / 6)
//                .setFractalLeaves(new FractalLeaves(this).setMaterial(Material.AIR));
//        break;
//    case RED_MUSHROOM_BASE:
//        this.setBaseHeight(3)
//                .setBaseThickness(3.5f)
//                .setThicknessDecrement(0)
//                .setMaxDepth(1)
//                .setFractalThreshold(4)
//                .setLeafRadius(0)
//                .setLogType(Material.MUSHROOM_STEM)
//                .setLengthDecrement(0)
//                .setMinBend(0.4 * Math.PI / 6)
//                .setMaxBend(0.6 * Math.PI / 6)
//                .setFractalLeaves(new FractalLeaves(this).setMaterial(Material.AIR));
//        break;
//    case GIANT_PUMPKIN:
//        this.setBaseHeight(6)
//                .setBaseThickness(1)
//                .setThicknessDecrement(1f)
//                .setMaxDepth(0)
//                .setLeafRadius(4)
//                .setLengthDecrement(-0.5f)
//                .setHeightVariation(0)
//                .setLogType(Material.OAK_LOG)
//                .setFractalLeaves(new FractalLeaves(this)
//                        .setMaterial(Material.PUMPKIN));
//    case FIRE_CORAL:
//        this.setBaseHeight(2)
//                .setInitialTilt(Math.PI / 2)
//                .setBaseThickness(1)
//                .setThicknessDecrement(0)
//                .setMaxDepth(3)
//                .setLeafRadiusX(1)
//                .setLeafRadiusZ(1)
//                .setLeafRadiusY(4)
//                .setLogType(Material.FIRE_CORAL_BLOCK)
//                .setLengthDecrement(-2f)
//                .setHeightVariation(0)
//                .setMaxBend(Math.PI / 2)
//                .setMinBend(Math.PI / 2.5)
//                .setMaxPitch(Math.PI)
//                .setMinPitch(0)
//                .setCoralDecoration(true)
//                .setFractalLeaves(new FractalLeaves(this)
//                        .setMaterial(Material.FIRE_CORAL_BLOCK));
//        break;
//    case HORN_CORAL:
//        this.setBaseHeight(2)
//                .setBaseThickness(2)
//                .setThicknessDecrement(0)
//                .setMaxDepth(3)
//                .setLeafRadiusX(3)
//                .setLeafRadiusZ(3)
//                .setLeafRadiusY(1)
//                .setLogType(Material.HORN_CORAL_BLOCK)
//                .setLengthDecrement(-1)
//                .setHeightVariation(0)
//                .setMaxBend(Math.PI / 3)
//                .setMinBend(Math.PI / 4)
//                .setMaxPitch(Math.PI)
//                .setMinPitch(0)
//                .setCoralDecoration(true)
//                .setNoMainStem(true)
//                .setFractalLeaves(new FractalLeaves(this)
//                        .setMaterial(Material.HORN_CORAL_BLOCK));
//        break;
//    case BRAIN_CORAL:
//        this.setBaseHeight(1)
//                .setBaseThickness(1)
//                .setThicknessDecrement(0f)
//                .setMaxDepth(3)
//                .setLeafRadiusX(1)
//                .setLeafRadiusZ(2)
//                .setLeafRadiusY(1)
//                .setLogType(Material.BRAIN_CORAL_BLOCK)
//                .setLengthDecrement(0)
//                .setHeightVariation(0)
//                .setFractalThreshold(3)
//                .setMaxBend(Math.PI / 3)
//                .setMinBend(Math.PI / 4)
//                .setMaxPitch(Math.PI)
//                .setMinPitch(0)
//                .setCoralDecoration(true)
//                .setHollowLeaves(0.9)
//                .setFractalLeaves(new FractalLeaves(this)
//                        .setMaterial(Material.BRAIN_CORAL_BLOCK));
//        break;
//    case TUBE_CORAL:
//        this.setBaseHeight(3)
//                .setAlwaysOneStraight(3)
//                .setBaseThickness(3)
//                .setThicknessDecrement(0f)
//                .setMaxDepth(3)
//                .setLeafRadiusX(1)
//                .setLeafRadiusZ(1)
//                .setLeafRadiusY(1)
//                .setLogType(Material.TUBE_CORAL_BLOCK)
//                .setLengthDecrement(0)
//                .setHeightVariation(1)
//                .setMaxBend(Math.PI / 3)
//                .setMinBend(Math.PI / 4)
//                .setMaxPitch(Math.PI)
//                .setMinPitch(0)
//                .setCoralDecoration(true)
//                .setHollowLeaves(0.9)
//                .setFractalLeaves(new FractalLeaves(this)
//                        .setMaterial(Material.TUBE_CORAL_BLOCK));
//        break;
//    case BUBBLE_CORAL:
//        this.setBaseHeight(3)
//                .setBaseThickness(1)
//                .setThicknessDecrement(0f)
//                .setMaxDepth(3)
//                .setLeafRadiusX(3)
//                .setLeafRadiusZ(3)
//                .setLeafRadiusY(3)
//                .setLogType(Material.BUBBLE_CORAL_BLOCK)
//                .setLengthDecrement(-1)
//                .setHeightVariation(1)
//                .setMaxBend(Math.PI / 2)
//                .setMinBend(Math.PI / 3)
//                .setMaxPitch(Math.PI)
//                .setMinPitch(0)
//                .setCoralDecoration(true)
//                .setHollowLeaves(0.9)
//                .setNoMainStem(true)
//                .setFractalLeaves(new FractalLeaves(this)
//                        .setMaterial(Material.BUBBLE_CORAL_BLOCK));
//        break;
}
