package org.terraform.tree;

public enum FractalTreeType {
	FOREST,
	NORMAL_SMALL,
	TAIGA_BIG,
	TAIGA_SMALL,
	SAVANNA_SMALL,
	SAVANNA_BIG,
	BROWN_MUSHROOM,
	WASTELAND_BIG,
	WASTELAND_COLLAPSED,
	SWAMP_TOP,
	SWAMP_BOTTOM, 
	BIRCH_BIG, 
	BIRCH_SMALL,
	JUNGLE_BIG,
	JUNGLE_SMALL, 
	COCONUT_TOP, 
	GIANT_PUMPKIN,
	DARK_OAK_BIG_TOP,
	DARK_OAK_BIG_BOTTOM
	;
}
