package org.terraform.tree;

public enum FractalTreeType {
	FOREST,
	NORMAL_SMALL,
	TAIGA_BIG,
	TAIGA_SMALL,
	SAVANNA_SMALL,
	SAVANNA_BIG,
	BROWN_MUSHROOM,
	WASTELAND_BIG,
	WASTELAND_COLLAPSED,
	SWAMP_TOP,
	SWAMP_BOTTOM, 
	BIRCH_BIG, 
	BIRCH_SMALL,
	JUNGLE_BIG,
	JUNGLE_SMALL, COCONUT_TOP, COCONUT_BOTTOM
	;
}
