package org.terraform.v1_21_R6;

import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.BuiltInLootTables;
import org.terraform.coregen.TerraLootTable;

import java.util.HashMap;

public class LootTableTranslator {

    // I am indeed formally trained to properly structure my code
    // I have however elected to completely ignore said training here
    // 28/3/2025 this fucking comment will follow me forever
    public static final HashMap<TerraLootTable, ResourceKey<LootTable>> translationMap = new HashMap<>() {{
        put(TerraLootTable.SPAWN_BONUS_CHEST, BuiltInLootTables.SPAWN_BONUS_CHEST);
        put(TerraLootTable.END_CITY_TREASURE, BuiltInLootTables.END_CITY_TREASURE);
        put(TerraLootTable.SIMPLE_DUNGEON, BuiltInLootTables.SIMPLE_DUNGEON);
        put(TerraLootTable.VILLAGE_WEAPONSMITH, BuiltInLootTables.VILLAGE_WEAPONSMITH);
        put(TerraLootTable.VILLAGE_TOOLSMITH, BuiltInLootTables.VILLAGE_TOOLSMITH);
        put(TerraLootTable.VILLAGE_ARMORER, BuiltInLootTables.VILLAGE_ARMORER);
        put(TerraLootTable.VILLAGE_CARTOGRAPHER, BuiltInLootTables.VILLAGE_CARTOGRAPHER);
        put(TerraLootTable.VILLAGE_MASON, BuiltInLootTables.VILLAGE_MASON);
        put(TerraLootTable.VILLAGE_SHEPHERD, BuiltInLootTables.VILLAGE_SHEPHERD);
        put(TerraLootTable.VILLAGE_BUTCHER, BuiltInLootTables.VILLAGE_BUTCHER);
        put(TerraLootTable.VILLAGE_FLETCHER, BuiltInLootTables.VILLAGE_FLETCHER);
        put(TerraLootTable.VILLAGE_FISHER, BuiltInLootTables.VILLAGE_FISHER);
        put(TerraLootTable.VILLAGE_TANNERY, BuiltInLootTables.VILLAGE_TANNERY);
        put(TerraLootTable.VILLAGE_TEMPLE, BuiltInLootTables.VILLAGE_TEMPLE);
        put(TerraLootTable.VILLAGE_DESERT_HOUSE, BuiltInLootTables.VILLAGE_DESERT_HOUSE);
        put(TerraLootTable.VILLAGE_PLAINS_HOUSE, BuiltInLootTables.VILLAGE_PLAINS_HOUSE);
        put(TerraLootTable.VILLAGE_TAIGA_HOUSE, BuiltInLootTables.VILLAGE_TAIGA_HOUSE);
        put(TerraLootTable.VILLAGE_SNOWY_HOUSE, BuiltInLootTables.VILLAGE_SNOWY_HOUSE);
        put(TerraLootTable.VILLAGE_SAVANNA_HOUSE, BuiltInLootTables.VILLAGE_SAVANNA_HOUSE);
        put(TerraLootTable.ABANDONED_MINESHAFT, BuiltInLootTables.ABANDONED_MINESHAFT);
        put(TerraLootTable.NETHER_BRIDGE, BuiltInLootTables.NETHER_BRIDGE);
        put(TerraLootTable.STRONGHOLD_LIBRARY, BuiltInLootTables.STRONGHOLD_LIBRARY);
        put(TerraLootTable.STRONGHOLD_CROSSING, BuiltInLootTables.STRONGHOLD_CROSSING);
        put(TerraLootTable.STRONGHOLD_CORRIDOR, BuiltInLootTables.STRONGHOLD_CORRIDOR);
        put(TerraLootTable.DESERT_PYRAMID, BuiltInLootTables.DESERT_PYRAMID);
        put(TerraLootTable.JUNGLE_TEMPLE, BuiltInLootTables.JUNGLE_TEMPLE);
        put(TerraLootTable.JUNGLE_TEMPLE_DISPENSER, BuiltInLootTables.JUNGLE_TEMPLE_DISPENSER);
        put(TerraLootTable.IGLOO_CHEST, BuiltInLootTables.IGLOO_CHEST);
        put(TerraLootTable.WOODLAND_MANSION, BuiltInLootTables.WOODLAND_MANSION);
        put(TerraLootTable.UNDERWATER_RUIN_SMALL, BuiltInLootTables.UNDERWATER_RUIN_SMALL);
        put(TerraLootTable.UNDERWATER_RUIN_BIG, BuiltInLootTables.UNDERWATER_RUIN_BIG);
        put(TerraLootTable.BURIED_TREASURE, BuiltInLootTables.BURIED_TREASURE);
        put(TerraLootTable.SHIPWRECK_MAP, BuiltInLootTables.SHIPWRECK_MAP);
        put(TerraLootTable.SHIPWRECK_SUPPLY, BuiltInLootTables.SHIPWRECK_SUPPLY);
        put(TerraLootTable.SHIPWRECK_TREASURE, BuiltInLootTables.SHIPWRECK_TREASURE);
        put(TerraLootTable.PILLAGER_OUTPOST, BuiltInLootTables.PILLAGER_OUTPOST);
        put(TerraLootTable.BASTION_TREASURE, BuiltInLootTables.BASTION_TREASURE);
        put(TerraLootTable.BASTION_OTHER, BuiltInLootTables.BASTION_OTHER);
        put(TerraLootTable.BASTION_BRIDGE, BuiltInLootTables.BASTION_BRIDGE);
        put(TerraLootTable.BASTION_HOGLIN_STABLE, BuiltInLootTables.BASTION_HOGLIN_STABLE);
        put(TerraLootTable.ANCIENT_CITY, BuiltInLootTables.ANCIENT_CITY);
        put(TerraLootTable.ANCIENT_CITY_ICE_BOX, BuiltInLootTables.ANCIENT_CITY_ICE_BOX);
        put(TerraLootTable.RUINED_PORTAL, BuiltInLootTables.RUINED_PORTAL);
        put(TerraLootTable.TRIAL_CHAMBERS_REWARD, BuiltInLootTables.TRIAL_CHAMBERS_REWARD);
        put(TerraLootTable.TRIAL_CHAMBERS_REWARD_COMMON, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_COMMON);
        put(TerraLootTable.TRIAL_CHAMBERS_REWARD_RARE, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_RARE);
        put(TerraLootTable.TRIAL_CHAMBERS_REWARD_UNIQUE, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_UNIQUE);
        put(TerraLootTable.TRIAL_CHAMBERS_REWARD_OMINOUS, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_OMINOUS);
        put(TerraLootTable.TRIAL_CHAMBERS_REWARD_OMINOUS_COMMON, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_OMINOUS_COMMON);
        put(TerraLootTable.TRIAL_CHAMBERS_REWARD_OMINOUS_RARE, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_OMINOUS_RARE);
        put(TerraLootTable.TRIAL_CHAMBERS_REWARD_OMINOUS_UNIQUE, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_OMINOUS_UNIQUE);
        put(TerraLootTable.TRIAL_CHAMBERS_SUPPLY, BuiltInLootTables.TRIAL_CHAMBERS_SUPPLY);
        put(TerraLootTable.TRIAL_CHAMBERS_CORRIDOR, BuiltInLootTables.TRIAL_CHAMBERS_CORRIDOR);
        put(TerraLootTable.TRIAL_CHAMBERS_INTERSECTION, BuiltInLootTables.TRIAL_CHAMBERS_INTERSECTION);
        put(TerraLootTable.TRIAL_CHAMBERS_INTERSECTION_BARREL, BuiltInLootTables.TRIAL_CHAMBERS_INTERSECTION_BARREL);
        put(TerraLootTable.TRIAL_CHAMBERS_ENTRANCE, BuiltInLootTables.TRIAL_CHAMBERS_ENTRANCE);
        put(TerraLootTable.TRIAL_CHAMBERS_CORRIDOR_DISPENSER, BuiltInLootTables.TRIAL_CHAMBERS_CORRIDOR_DISPENSER);
        put(TerraLootTable.TRIAL_CHAMBERS_CHAMBER_DISPENSER, BuiltInLootTables.TRIAL_CHAMBERS_CHAMBER_DISPENSER);
        put(TerraLootTable.TRIAL_CHAMBERS_WATER_DISPENSER, BuiltInLootTables.TRIAL_CHAMBERS_WATER_DISPENSER);
        put(TerraLootTable.TRIAL_CHAMBERS_CORRIDOR_POT, BuiltInLootTables.TRIAL_CHAMBERS_CORRIDOR_POT);
        put(TerraLootTable.EQUIPMENT_TRIAL_CHAMBER, BuiltInLootTables.EQUIPMENT_TRIAL_CHAMBER);
        put(TerraLootTable.EQUIPMENT_TRIAL_CHAMBER_RANGED, BuiltInLootTables.EQUIPMENT_TRIAL_CHAMBER_RANGED);
        put(TerraLootTable.EQUIPMENT_TRIAL_CHAMBER_MELEE, BuiltInLootTables.EQUIPMENT_TRIAL_CHAMBER_MELEE);
        put(TerraLootTable.FISHING, BuiltInLootTables.FISHING);
        put(TerraLootTable.FISHING_JUNK, BuiltInLootTables.FISHING_JUNK);
        put(TerraLootTable.FISHING_TREASURE, BuiltInLootTables.FISHING_TREASURE);
        put(TerraLootTable.FISHING_FISH, BuiltInLootTables.FISHING_FISH);
        put(TerraLootTable.CAT_MORNING_GIFT, BuiltInLootTables.CAT_MORNING_GIFT);
        put(TerraLootTable.ARMORER_GIFT, BuiltInLootTables.ARMORER_GIFT);
        put(TerraLootTable.BUTCHER_GIFT, BuiltInLootTables.BUTCHER_GIFT);
        put(TerraLootTable.CARTOGRAPHER_GIFT, BuiltInLootTables.CARTOGRAPHER_GIFT);
        put(TerraLootTable.CLERIC_GIFT, BuiltInLootTables.CLERIC_GIFT);
        put(TerraLootTable.FARMER_GIFT, BuiltInLootTables.FARMER_GIFT);
        put(TerraLootTable.FISHERMAN_GIFT, BuiltInLootTables.FISHERMAN_GIFT);
        put(TerraLootTable.FLETCHER_GIFT, BuiltInLootTables.FLETCHER_GIFT);
        put(TerraLootTable.LEATHERWORKER_GIFT, BuiltInLootTables.LEATHERWORKER_GIFT);
        put(TerraLootTable.LIBRARIAN_GIFT, BuiltInLootTables.LIBRARIAN_GIFT);
        put(TerraLootTable.MASON_GIFT, BuiltInLootTables.MASON_GIFT);
        put(TerraLootTable.SHEPHERD_GIFT, BuiltInLootTables.SHEPHERD_GIFT);
        put(TerraLootTable.TOOLSMITH_GIFT, BuiltInLootTables.TOOLSMITH_GIFT);
        put(TerraLootTable.WEAPONSMITH_GIFT, BuiltInLootTables.WEAPONSMITH_GIFT);
        put(TerraLootTable.UNEMPLOYED_GIFT, BuiltInLootTables.UNEMPLOYED_GIFT);
        put(TerraLootTable.BABY_VILLAGER_GIFT, BuiltInLootTables.BABY_VILLAGER_GIFT);
        put(TerraLootTable.SNIFFER_DIGGING, BuiltInLootTables.SNIFFER_DIGGING);
        put(TerraLootTable.PANDA_SNEEZE, BuiltInLootTables.PANDA_SNEEZE);
        put(TerraLootTable.CHICKEN_LAY, BuiltInLootTables.CHICKEN_LAY);
        put(TerraLootTable.ARMADILLO_SHED, BuiltInLootTables.ARMADILLO_SHED);
        //        put(TerraLootTable.TURTLE_GROW, BuiltInLootTables.TURTLE_GROW);
        //        put(TerraLootTable.HARVEST_CAVE_VINE, BuiltInLootTables.HARVEST_CAVE_VINE);
        //        put(TerraLootTable.HARVEST_SWEET_BERRY_BUSH, BuiltInLootTables.HARVEST_SWEET_BERRY_BUSH);
        //        put(TerraLootTable.HARVEST_BEEHIVE, BuiltInLootTables.HARVEST_BEEHIVE);
        //        put(TerraLootTable.CARVE_PUMPKIN, BuiltInLootTables.CARVE_PUMPKIN);
        put(TerraLootTable.PIGLIN_BARTERING, BuiltInLootTables.PIGLIN_BARTERING);
        put(TerraLootTable.SPAWNER_TRIAL_CHAMBER_KEY, BuiltInLootTables.SPAWNER_TRIAL_CHAMBER_KEY);
        put(TerraLootTable.SPAWNER_TRIAL_CHAMBER_CONSUMABLES, BuiltInLootTables.SPAWNER_TRIAL_CHAMBER_CONSUMABLES);
        put(TerraLootTable.SPAWNER_OMINOUS_TRIAL_CHAMBER_KEY, BuiltInLootTables.SPAWNER_OMINOUS_TRIAL_CHAMBER_KEY);
        put(TerraLootTable.SPAWNER_OMINOUS_TRIAL_CHAMBER_CONSUMABLES, BuiltInLootTables.SPAWNER_OMINOUS_TRIAL_CHAMBER_CONSUMABLES);
        put(TerraLootTable.SPAWNER_TRIAL_ITEMS_TO_DROP_WHEN_OMINOUS, BuiltInLootTables.SPAWNER_TRIAL_ITEMS_TO_DROP_WHEN_OMINOUS);
        //        put(TerraLootTable.ARMADILLO_BRUSH, BuiltInLootTables.ARMADILLO_BRUSH);
        put(TerraLootTable.BOGGED_SHEAR, BuiltInLootTables.BOGGED_SHEAR);
        put(TerraLootTable.SHEAR_MOOSHROOM, BuiltInLootTables.SHEAR_MOOSHROOM);
        put(TerraLootTable.SHEAR_RED_MOOSHROOM, BuiltInLootTables.SHEAR_RED_MOOSHROOM);
        put(TerraLootTable.SHEAR_BROWN_MOOSHROOM, BuiltInLootTables.SHEAR_BROWN_MOOSHROOM);
        put(TerraLootTable.SHEAR_SNOW_GOLEM, BuiltInLootTables.SHEAR_SNOW_GOLEM);
        put(TerraLootTable.SHEAR_SHEEP, BuiltInLootTables.SHEAR_SHEEP);
        //        put(TerraLootTable.CHARGED_CREEPER, BuiltInLootTables.CHARGED_CREEPER);
        //        put(TerraLootTable.CHARGED_CREEPER_PIGLIN, BuiltInLootTables.CHARGED_CREEPER_PIGLIN);
        //        put(TerraLootTable.CHARGED_CREEPER_CREEPER, BuiltInLootTables.CHARGED_CREEPER_CREEPER);
        //        put(TerraLootTable.CHARGED_CREEPER_SKELETON, BuiltInLootTables.CHARGED_CREEPER_SKELETON);
        //        put(TerraLootTable.CHARGED_CREEPER_WITHER_SKELETON, BuiltInLootTables.CHARGED_CREEPER_WITHER_SKELETON);
        //        put(TerraLootTable.CHARGED_CREEPER_ZOMBIE, BuiltInLootTables.CHARGED_CREEPER_ZOMBIE);
        put(TerraLootTable.DESERT_WELL_ARCHAEOLOGY, BuiltInLootTables.DESERT_WELL_ARCHAEOLOGY);
        put(TerraLootTable.DESERT_PYRAMID_ARCHAEOLOGY, BuiltInLootTables.DESERT_PYRAMID_ARCHAEOLOGY);
        put(TerraLootTable.TRAIL_RUINS_ARCHAEOLOGY_COMMON, BuiltInLootTables.TRAIL_RUINS_ARCHAEOLOGY_COMMON);
        put(TerraLootTable.TRAIL_RUINS_ARCHAEOLOGY_RARE, BuiltInLootTables.TRAIL_RUINS_ARCHAEOLOGY_RARE);
        put(TerraLootTable.OCEAN_RUIN_WARM_ARCHAEOLOGY, BuiltInLootTables.OCEAN_RUIN_WARM_ARCHAEOLOGY);
        put(TerraLootTable.OCEAN_RUIN_COLD_ARCHAEOLOGY, BuiltInLootTables.OCEAN_RUIN_COLD_ARCHAEOLOGY);
    }};

}
