package org.terraform.v1_19_R1;

import org.bukkit.entity.EntityType;
import org.terraform.main.TerraformGeneratorPlugin;

public class EntityTypeMapper {

	public static String getObfsNameFromBukkitEntityType(EntityType e){
		switch(e) {
		case ALLAY:
			return "b";
		case AREA_EFFECT_CLOUD:
			return "c";
		case ARMOR_STAND:
			return "d";
		case ARROW:
			return "e";
		case AXOLOTL:
			return "f";
		case BAT:
			return "g";
		case BEE:
			return "h";
		case BLAZE:
			return "i";
		case BOAT:
			return "j";
		case CHEST_BOAT:
			return "k";
		case CAT:
			return "l";
		case CAVE_SPIDER:
			return "m";
		case CHICKEN:
			return "n";
		case COD:
			return "o";
		case COW:
			return "p";
		case CREEPER:
			return "q";
		case DOLPHIN:
			return "r";
		case DONKEY:
			return "s";
		case DRAGON_FIREBALL:
			return "t";
		case DROWNED:
			return "u";
		case ELDER_GUARDIAN:
			return "v";
		case ENDER_CRYSTAL:
			return "w";
		case ENDER_DRAGON:
			return "x";
		case ENDERMAN:
			return "y";
		case ENDERMITE:
			return "z";
		case EVOKER:
			return "A";
		case EVOKER_FANGS:
			return "B";
		case EXPERIENCE_ORB:
			return "C";
//		case EYE_OF_ENDER:
//			return "D";
		case FALLING_BLOCK:
			return "E";
		case FIREWORK:
			return "F";
		case FOX:
			return "G";
		case FROG:
			return "H";
		case GHAST:
			return "I";
		case GIANT:
			return "J";
		case GLOW_ITEM_FRAME:
			return "K";
		case GLOW_SQUID:
			return "L";
		case GOAT:
			return "M";
		case GUARDIAN:
			return "N";
		case HOGLIN:
			return "O";
		case HORSE:
			return "P";
		case HUSK:
			return "Q";
		case ILLUSIONER:
			return "R";
		case IRON_GOLEM:
			return "S";
		case DROPPED_ITEM:
			return "T";
		case ITEM_FRAME:
			return "U";
		case FIREBALL:
			return "V";
		case LEASH_HITCH:
			return "W";
		case LIGHTNING:
			return "X";
		case LLAMA:
			return "Y";
		case LLAMA_SPIT:
			return "Z";
		case MAGMA_CUBE:
			return "aa";
		case MARKER:
			return "ab";
		case MINECART:
			return "ac";
		case MINECART_CHEST:
			return "ad";
		case MINECART_COMMAND:
			return "ae";
		case MINECART_FURNACE:
			return "af";
		case MINECART_HOPPER:
			return "ag";
		case MINECART_MOB_SPAWNER:
			return "ah";
		case MINECART_TNT:
			return "ai";
		case MULE:
			return "aj";
		case MUSHROOM_COW:
			return "ak";
		case OCELOT:
			return "al";
		case PAINTING:
			return "am";
		case PANDA:
			return "an";
		case PARROT:
			return "ao";
		case PHANTOM:
			return "ap";
		case PIG:
			return "aq";
		case PIGLIN:
			return "ar";
		case PIGLIN_BRUTE:
			return "as";
		case PILLAGER:
			return "at";
		case POLAR_BEAR:
			return "au";
		case PRIMED_TNT:
			return "av";
		case PUFFERFISH:
			return "aw";
		case RABBIT:
			return "ax";
		case RAVAGER:
			return "ay";
		case SALMON:
			return "az";
		case SHEEP:
			return "aA";
		case SHULKER:
			return "aB";
		case SHULKER_BULLET:
			return "aC";
		case SILVERFISH:
			return "aD";
		case SKELETON:
			return "aE";
		case SKELETON_HORSE:
			return "aF";
		case SLIME:
			return "aG";
		case SMALL_FIREBALL:
			return "aH";
		case SNOWMAN:
			return "aI";
		case SNOWBALL:
			return "aJ";
		case SPECTRAL_ARROW:
			return "aK";
		case SPIDER:
			return "aL";
		case SQUID:
			return "aM";
		case STRAY:
			return "aN";
		case STRIDER:
			return "aO";
		case TADPOLE:
			return "aP";
		case EGG:
			return "aQ";
		case ENDER_PEARL:
			return "aR";
		case THROWN_EXP_BOTTLE:
			return "aS";
		case SPLASH_POTION:
			return "aT";
		case TRIDENT:
			return "aU";
		case TRADER_LLAMA:
			return "aV";
		case TROPICAL_FISH:
			return "aW";
		case TURTLE:
			return "aX";
		case VEX:
			return "aY";
		case VILLAGER:
			return "aZ";
		case VINDICATOR:
			return "ba";
		case WANDERING_TRADER:
			return "bb";
		case WARDEN:
			return "bc";
		case WITCH:
			return "bd";
		case WITHER:
			return "be";
		case WITHER_SKELETON:
			return "bf";
		case WITHER_SKULL:
			return "bg";
		case WOLF:
			return "bh";
		case ZOGLIN:
			return "bi";
		case ZOMBIE:
			return "bj";
		case ZOMBIE_HORSE:
			return "bk";
		case ZOMBIE_VILLAGER:
			return "bl";
		case ZOMBIFIED_PIGLIN:
			return "bm";
		case PLAYER:
			return "bn";
		case FISHING_HOOK:
			return "bo";
		case ENDER_SIGNAL:
		case UNKNOWN:
			break;
		}
		TerraformGeneratorPlugin.logger.error("INVALID ENTITY REQUESTED: " + e.toString());
		return "";
	}
}
