name: TerraformGenerator
author: Hex_27
version: 14.0.1
api-version: 1.18
description: World Generator
main: org.terraform.main.TerraformGeneratorPlugin
load: STARTUP
commands:
  terraform:
    description: Main command
    aliases: terra