name: MysticBiomes
author: BadgersMC
version: 16.2.0
api-version: 1.18
description: World Generator for play.mysticdominions.com
main: org.terraform.main.TerraformGeneratorPlugin
load: STARTUP
folia-supported: true
commands:
  terraform:
    description: Main command
    aliases: terra