name: TerraformGenerator
author: Hex_27
version: 26.1.0
api-version: 1.18
description: World Generator
folia-supported: false
main: org.terraform.main.TerraformGeneratorPlugin
load: STARTUP
commands:
  terraform:
    description: Main command
    aliases: terra