name: TerraformGenerator
author: Hex_27
version: 27.0.1
api-version: 1.18
description: World Generator
folia-supported: true
main: org.terraform.main.TerraformGeneratorPlugin
load: STARTUP
commands:
  terraform:
    description: Main command
    aliases: terra